### PR TITLE
Corrections in the docs 

### PR DESCRIPTION
**Pull request by DmitryV2044**
Made some grammar correction in the docs.
Affected "Getting Started" and "Contribution" sections

### CODE REVIEW

**Comment by bleudev** [comment]
Where is checklist?

**Comment by DmitryV2044** [comment]
What do you mean? 
How does it look like?

**Comment by bleudev** [comment]
ex,
- [ ] 1 fix
- [x] 2 fix

**Comment by DmitryV2044** [comment]
- [x] Added missing prepositions
- [x] Picked up more correct figures of speech
- [x] Changed forms of some verbs

**Pull request merged**
